-- Adds a curated takeaways column to gk_editorials.
-- Each editorial gets exactly 4 exam-ready takeaways generated by the
-- generate-editorial-takeaways Edge Function. Front-end renders the
-- "Key GK Takeaways for CLAT" box only when this column is non-empty.

ALTER TABLE public.gk_editorials
  ADD COLUMN IF NOT EXISTS takeaways jsonb DEFAULT NULL;

COMMENT ON COLUMN public.gk_editorials.takeaways IS
  'Array of 4 curated CLAT-focused takeaways (polity / IR / legal / impact angles). NULL until backfilled.';
